title: 광장 연습 / 녹음실
email: pilotedeguerre@gmail.com
description: 백남준아트센터 7월 12일 설치 시작. 전시 - 손에 폰잡고 - 광장연습(Phone-in-hand - Choir Practice)의 목소리 녹음용 사이트. mobile(특히, iOS)에서는 작동하지 않을 수 있습니다.
url: "/njp-vjkl"
production_url : https://applecargo.github.io/njp-vjkl
BASE_PATH : https://applecargo.github.io/njp-vjkl

# Build settings
name: phone-in-hand
markdown: kramdown
host: 0.0.0.0
port: 3000
gems:
excerpt_seperator: "<!--more-->"
destination: "./build"
permalink: "/:title/"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - ".gitignore"
  - components
  - js/source.js
  - webpack.config.js
  - package.json
  - .jshintrc
  - .sass-cache
  - browser-sync.js
  - npm-debug.log
  - README.md
sass:
  style: compressed

# Collections
collections:
  posts:
    title: Posts
    output: true
    permalink: "/news/:title"

# Pages
include: ["_pages"]
